# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginRegister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('travelto', models.DateField()),
                ('travelfrom', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='loginRegister.User')),
                ('travellers', models.ManyToManyField(related_name='travellers', to='loginRegister.User')),
            ],
            managers=[
                ('travelManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
